/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CertificationManager__factory } from "./CertificationManager__factory";
export { PrescriptionManager__factory } from "./PrescriptionManager__factory";
