/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CertificationManager } from "./CertificationManager";
export type { PrescriptionManager } from "./PrescriptionManager";
